# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: From Ruins
email: drew@drewmistak.com
description: Masculine self-development
url: "http://fromruins.com" # the base hostname & protocol for your site
twitter: "https://twitter.com/drewmistak"
twitter-handle: "drewmistak"

permalink: "/:categories/:title"
excerpt_separator: <!--excerpt_end-->

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Serving
port: 4000
host: 0.0.0.0

gems:
  - jekyll-sitemap
